name: Moodle Task

on:
  schedule:
    - cron: '0 2 * * 1'

jobs:
  run-task:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          # Si tienes dependencias adicionales, agrégalas aquí, como requests
          pip install requests

      - name: Run Python script
        run: |
          python your-script.py  # Reemplaza por el nombre de tu script
